### ISSUE TITLE
ImportError: cannot import name utils Error on the examples

### ISSUE THREAD

**Issue by bmccorm2** [fitoprincipe/ipygee#1]
More of a question than an issue - but I am having issues getting just the simple examples to work.  Here is a picture of my notebook and below is the error I get.  Do you know if i am doing anything wrong?

Thanks for any help!

![image](https://user-images.githubusercontent.com/11781610/59310646-47c19d00-8c64-11e9-9122-452d36e42861.png)

```
ImportErrorTraceback (most recent call last)
<ipython-input-25-7aba34c2572e> in <module>()
----> 1 from ipygee import *

/usr/local/lib/python2.7/dist-packages/ipygee/__init__.py in <module>()
      5 
      6 from ._version import __version__
----> 7 from .map import Map
      8 from .assets import AssetManager
      9 from .tasks import TaskManager

/usr/local/lib/python2.7/dist-packages/ipygee/map.py in <module>()
      8 from traitlets import *
      9 from collections import OrderedDict
---> 10 from .tasks import TaskManager
     11 from .assets import AssetManager
     12 from geetools import tools, utils

/usr/local/lib/python2.7/dist-packages/ipygee/tasks.py in <module>()
      5 import datetime
      6 from ipywidgets import *
----> 7 from . import utils
      8 from .threading import Thread
      9 import time

/usr/local/lib/python2.7/dist-packages/ipygee/utils.py in <module>()
      4 
      5 from ipywidgets import *
----> 6 from .dispatcher import dispatch
      7 import datetime
      8 

/usr/local/lib/python2.7/dist-packages/ipygee/dispatcher.py in <module>()
     10 import ee
     11 from ipywidgets import *
---> 12 from . import utils
     13 from geetools.ui.dispatcher import belongToEE
     14 

ImportError: cannot import name utils
```

**Comment by fitoprincipe** [comment]
Hi @bmccorm2,
I see you're using python 2.7, unfortunately I at the moment only works with python 3.5 and above. I'm not sure if spend time trying to make it work in older version since python 2.7 will end up soon. But if you really need to use that version, let me know and I'll see what I can do. 
Best
Rodrigo

**Comment by bmccorm2** [comment]
Yes you are right! So I am using the docker container (gcr.io/earthengine-project/datalab-ee:latest) and that defaults to 2.7.  Whenever I try to switch to python3 kernel it just hangs.  (screenshot below)  Do you know any way around this?  Or would you just recommend an alternative method of install?

![image](https://user-images.githubusercontent.com/11781610/59366703-f105a300-8cf7-11e9-9d99-895048f97ef6.png)

**Comment by fitoprincipe** [comment]
Do you need to use docker?? I've found it's much easier to use jupyter directly.. Anaconda makes it really easy in Windows, and in Linux you can create a python 3 virtual environment and install jupyter there. Installing EE API is not hard. I'm not sure if this package will run as expected in CloudDatalab... I may have a try just to see.. when I have the chance

**Comment by bmccorm2** [comment]
No it’s not necessary to use the container ... I just thought it would be easier. But since it’s not, let me try the install you suggested 🙂 I just left and won’t be able to try until Monday. I’ll report back then. Thanks for the suggestion!

**Comment by fitoprincipe** [comment]
Hi @bmccorm2, how did it go?

**Comment by bmccorm2** [comment]
Sorry for the late response - I ran into some other issues because of company firewalls so I had to do some other workarounds.....but I finally got it with the manual installation.  Now all the examples work with no issue! Thanks again for all your help!

**Comment by fitoprincipe** [comment]
Good to hear that! You're welcome =)

**Comment by gabezuckerman** [comment]
> Hi @bmccorm2,
> I see you're using python 2.7, unfortunately I at the moment only works with python 3.5 and above. I'm not sure if spend time trying to make it work in older version since python 2.7 will end up soon. But if you really need to use that version, let me know and I'll see what I can do.
> Best
> Rodrigo

I am having trouble using ee in python3.7 [in the first place](https://developers.google.com/earth-engine/python_install_manual#ubuntu-linux--mac-os-x-installation), how are we meant to get this to run?

**Comment by ditirodt** [comment]
I am running into the same problem `ModuleNotFoundError: No module named geetools.ui`
